# Generated by Django 3.2.5 on 2021-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='personnel',
            new_name='user',
        ),
    ]
