# Generated by Django 3.2.5 on 2021-08-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0003_rename_personnel_personnel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
