# Generated by Django 3.2.5 on 2021-08-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0004_medecin_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='unite',
        ),
    ]
