# Generated by Django 3.2.5 on 2021-08-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0005_remove_poste_unite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(choices=[('repeat', 'Répété'), ('fixed', 'Fixé')], default='repeat', max_length=15)),
                ('date', models.DateField()),
                ('en_service', models.BooleanField(default=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'lundi'), (1, 'mardi'), (2, 'mercredi'), (3, 'jeudi'), (4, 'vendredi'), (5, 'samedi'), (6, 'dimanche')], default=0)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('note', models.TextField()),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grh.personnel')),
            ],
        ),
    ]
