# Generated by Django 3.2.5 on 2021-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0006_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
