# Generated by Django 3.2.5 on 2021-09-02 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0006_alter_equipement_local'),
        ('grh', '0008_auto_20210831_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=100)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.batiment')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.personnel')),
            ],
        ),
        migrations.AlterField(
            model_name='poste',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grh.service'),
        ),
    ]
