# Generated by Django 3.2.5 on 2021-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0010_auto_20210904_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='localisation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
