# Generated by Django 3.2.5 on 2021-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0011_periode_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilspecialiste',
            name='expertise',
        ),
        migrations.AddField(
            model_name='profilspecialiste',
            name='date_obtention',
            field=models.DateField(default=None, null=True),
        ),
    ]
