# Generated by Django 3.2.5 on 2021-09-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0012_auto_20210906_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilspecialiste',
            name='medecin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grh.medecin'),
        ),
    ]
