# Generated by Django 3.2.5 on 2021-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0014_personnel_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='duree',
            field=models.CharField(default='', max_length=50),
        ),
    ]
