# Generated by Django 3.2.5 on 2021-09-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0015_alter_stage_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='batiment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='chef',
        ),
    ]
