# Generated by Django 3.2.5 on 2021-09-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0016_auto_20210907_1050'),
        ('plateau_technique', '0009_service'),
        ('consultation', '0012_alter_consultation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
