# Generated by Django 3.2.5 on 2021-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0018_personnel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='should_update_password',
            field=models.BooleanField(default=True),
        ),
    ]
