# Generated by Django 3.2.5 on 2021-08-01 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('surface', models.PositiveIntegerField(blank=True, default=None, help_text='En mètres carré', null=True)),
                ('localisation', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('classe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/infrastructures')),
                ('localisation', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('site_web', models.URLField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('directeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grh.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('supericie', models.PositiveIntegerField(blank=True, default=None, help_text='En mètres carré', null=True)),
                ('localisation', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('batiment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DIRECTION MEDICALE', 'Direction médicale'), ('DIRECTION PARAMÉDICALE', 'Direction paramédicale'), ('SERVICE URGENCES', 'Service des Urgences'), ('SERVICE CONSULTATIONS  Externes & Soins ambulatoires', 'Service des Consultations  Externes & Soins ambulatoires'), ('SERVICE HOSPITALISATION', 'SERVICE DES HOSPITALISATION'), ('SERVICE BLOC TECHNIQUE', 'SERVICE BLOC TECHNIQUE'), ('SERVICE ANESTHESIE-REANIMATION', 'SERVICE D ANESTHESIE-REANIMATION'), ('SERVICE LABORATOIRE BIOMEDICAL', 'SERVICE DE LABORATOIRE BIOMEDICAL'), ('SERVICE IMAGERIE MEDICALE', 'SERVICE D IMAGERIE MEDICALE'), ('SERVICE IMAGERIE MEDICALE', 'SERVICE D IMAGERIE MEDICALE'), ('SERVICE PHYSIOTHERAPIE REEDUCATION FONCTIONNELLE', 'SERVICE DE PHYSIOTHERAPIE REEDUCATION FONCTIONNELLE'), ('SERVICE RADIOTHERAPIE', 'SERVICE DE RADIOTHERAPIE')], max_length=255)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='UniteMedicale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('URGENCE PREADMISION', 'Unité de Préadmission'), ('URGENCE MED', 'Unité des urgences médicales'), ('URGENCE CHIR', 'Unité des urgences chirurgicales'), ('CONSULT MED', 'Unité des Consultations médicales des explorations fonctionnelles'), ('CONSULT CHIR', 'Unité des Consultations chirurgicales'), ('GYN-OBST', 'Unité des Consultations gynéco-obstétricales'), ('CONSULT STOMATO', 'Unité des Consultations stomatologiques'), ('CONSULT OPHTALMO', 'Unité des Consultations ophtalmologiques'), ('CONSULT ORL', 'Unité des Consultations otorhinolaryngologiques '), ('HOSPI MED', 'Unité d hospitalisation médicale'), ('HOSPI CHIR', 'Unité d hospitalisation chirurgicale '), ('HOSPI GYN', 'Unité d hospitalisation Gynéco-obstétricale '), ('HOSPI PEDIA', 'Unité d hospitalisation pédiatrique '), ('HOSPI PEDIA', 'Unité d hospitalisation VIP '), ('HOSPI PSY', 'Unité d hospitalisation psychiatrique '), ('HOSPI REHABIL', 'Unité d hospitalisation réhabilitation '), ('HOSPI REA', 'Unité d hospitalisation Réanimation '), ('HOSPI HEMODIA', 'Unité d hospitalisation Hémodialyse '), ('BLOC OP', 'Unité Bloc opératoire '), ('BLOC STERI', 'Unité de Stérilisation centrale '), ('BLOC SPI', 'Unité de Stérilisation centrale '), ('BLOC OBST', 'Unité Bloc obstétrical '), ('ANESTH', 'Unité d anesthésie '), ('HOSPI REA', 'Unité de réanimation '), ('LAB ANALYSES', 'Unité d analyses biomédicales courantes '), ('LAB TRANSFUSION', 'Unité de Tansfusion sanguine '), ('LAB BIOMOLECULAIRE', 'Unité de biologie moléculaire '), ('IMAG RADIO', 'Unité de radiologie conventionnelle'), ('IMAG SCANNER', 'Unité  Scanner '), ('IMAG IRM', 'Unité IRM '), ('IMAG ECHO', 'Unité d échographie '), ('IMAG GAMMA', 'Unité Gamma camera '), ('ANAPATH HISTO', 'Unité d histopathologie '), ('ANAPATH MEDICO LEGAL', 'Unité de médecine légale '), ('PHYSIOTHER PHYSIO', 'Unité de Physiothérapie '), ('PHYSIOTHER KINE', 'Unité de Kinésithérapie '), ('PHYSIOTHER ERGOT', 'Unité d ergothérapie '), ('RADIOTHER EXT', 'Unité de radiothérapie externe '), ('RADIOTHER CONTACT', 'Unité de radiothérapie de contact '), ('RADIOTHER ISOTOPE', 'Unité de radiothérapie isotopique ')], max_length=255)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.local')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.personnel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.service')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceParking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('localisation', models.CharField(max_length=50)),
                ('Infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceHeliport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('localisation', models.CharField(max_length=50)),
                ('Infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('date_arrivage', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.local')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[("Équipement d'ambulance", "Équipement d'ambulance"), ("Équipement d'accueil", "Équipement d'accueil"), ('Équipement de consultation', 'Équipement de consultation'), ("Équipement d'urgence", "Équipement d'urgence"), ("Équipement d'hospitalisation", "Équipement d'hospitalisation"), ("Équipement d'analyses biomedicales", "Équipement d'analyses biomedicales"), ("Équipement d'anatomie pathologique", "Équipement d'anatomie pathologique"), ("Équipement d'imagerie medicale", "Équipement d'imagerie medicale"), ("Équipement d'explorations fonctionnelles", "Équipement d'explorations fonctionnelles"), ("Équipement d'endoscopie", "Équipement d'endoscopie"), ("Équipement d'electrodiagnositc", "Équipement d'electrodiagnositc"), ('Équipement de chirugie', 'Équipement de chirugie'), ("Équipement d'anesthesie", "Équipement d'anesthesie"), ('Équipement obstetrical', 'Équipement obstetrical'), ('Équipement de sterilisation', 'Équipement de sterilisation'), ('Équipement de reanimation', 'Équipement de reanimation'), ('Équipement de kinesitherapie', 'Équipement de kinesitherapie'), ('Équipement de morgue', 'Équipement de morgue'), ('autres Équipements', 'autres Équipements'), ('Livres de medecine', 'Livres de medecine')], default="Équipement d'ambulance", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantite', models.PositiveIntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.local')),
            ],
        ),
        migrations.AddField(
            model_name='batiment',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.infrastructure'),
        ),
    ]
