# Generated by Django 3.2.5 on 2021-08-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0003_alter_service_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='local',
        ),
    ]
