# Generated by Django 3.2.5 on 2021-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0004_remove_service_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lit',
            old_name='libre',
            new_name='est_libre',
        ),
        migrations.AddField(
            model_name='lit',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
