# Generated by Django 3.2.5 on 2021-08-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0005_auto_20210830_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateau_technique.local'),
        ),
    ]
