# Generated by Django 3.2.5 on 2021-09-02 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultation_service'),
        ('grh', '0009_auto_20210902_1119'),
        ('plateau_technique', '0006_alter_equipement_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='quantite',
        ),
        migrations.AddField(
            model_name='lit',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiel',
            name='numero_serie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materiel',
            name='type',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Medical', 'Médical'), ('Mobilier', 'Mobilier'), ('Electronique', 'Electronique'), ('Bureau', 'Bureau')], default='Medical', max_length=50),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
