# Generated by Django 3.2.5 on 2021-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0007_auto_20210902_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='latitude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='longitude',
            field=models.CharField(default='', max_length=50),
        ),
    ]
