# Generated by Django 3.2.5 on 2021-09-07 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0016_auto_20210907_1050'),
        ('plateau_technique', '0008_auto_20210904_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=100)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.batiment')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.personnel')),
            ],
        ),
    ]
