# Generated by Django 3.2.5 on 2021-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0009_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/batiments'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='iamge',
            field=models.ImageField(default=None, null=True, upload_to='images/equipements/'),
        ),
        migrations.AddField(
            model_name='lit',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/lits/'),
        ),
        migrations.AddField(
            model_name='local',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/locaux/'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/materiels/'),
        ),
    ]
