# Generated by Django 3.2.5 on 2021-09-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0019_personnel_should_update_password'),
        ('plateau_technique', '0010_auto_20210907_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructurePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_embauche', models.DateField(default=None, null=True)),
                ('infrastructure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateau_technique.infrastructure')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grh.personnel')),
            ],
        ),
    ]
