# Generated by Django 3.2.5 on 2021-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0012_alter_service_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/services'),
        ),
    ]
