# Generated by Django 3.2.5 on 2021-08-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiaps',
            name='service',
        ),
        migrations.AlterField(
            model_name='tiaps',
            name='type',
            field=models.CharField(choices=[('QUITTANCE', 'TIAPS pour Quittance'), ('AGV', 'TIAPS pour AGV'), ('BGS', 'TIAPS pour BGS'), ('BSC', 'TIAPS pour BSC')], default='QUITTANCE', max_length=10),
        ),
    ]
