# Generated by Django 3.2.5 on 2021-08-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_auto_20210817_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date_limite_validite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
