# Generated by Django 3.2.5 on 2021-08-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_alter_bon_date_limite_validite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date_limite_validite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
