# Generated by Django 3.2.5 on 2021-09-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_auto_20210817_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaps',
            name='date_consultation',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tiaps',
            name='heure_debut',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tiaps',
            name='heure_fin',
            field=models.TimeField(default=None, null=True),
        ),
    ]
