# Generated by Django 3.2.5 on 2021-08-01 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Consultation'), (1, 'Suivi')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Differentiel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maladie', models.CharField(max_length=255)),
                ('justificatif', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resultat', models.TextField(blank=True, default='')),
                ('est_fait', models.BooleanField(default=False)),
                ('est_sur_prescription', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TAILLE', 'Taille'), ('POIDS', 'Poids'), ('TEMPERATURE', 'Température'), ('PRESSION', 'PRESSION SANGUINE')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commentaire', models.TextField(blank=True)),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionExamen',
            fields=[
                ('prescription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consultation.prescription')),
                ('est_fait', models.BooleanField(default=False)),
            ],
            bases=('consultation.prescription',),
        ),
        migrations.CreateModel(
            name='PrescriptionMedicamenteuse',
            fields=[
                ('prescription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consultation.prescription')),
                ('medicament', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('frequence', models.CharField(max_length=50)),
                ('duree', models.DurationField()),
            ],
            bases=('consultation.prescription',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('prescription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consultation.prescription')),
                ('description', models.TextField()),
            ],
            bases=('consultation.prescription',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('resultat', models.CharField(max_length=50)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('duree', models.DurationField(blank=True, default='')),
                ('frequence', models.CharField(blank=True, default='', max_length=100)),
                ('intensité', models.CharField(blank=True, default='', max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
            ],
        ),
    ]
