# Generated by Django 3.2.5 on 2021-09-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0009_auto_20210902_1119'),
        ('consultation', '0003_consultation_en_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.service'),
        ),
    ]
