# Generated by Django 3.2.5 on 2021-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='type',
            field=models.CharField(choices=[('Taille', 'Taille'), ('Poids', 'Poids'), ('Température', 'Température'), ('Pression', 'Pression Sanguine')], max_length=20),
        ),
    ]
