# Generated by Django 3.2.5 on 2021-09-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_alter_parametre_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptome',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='symptome',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
