# Generated by Django 3.2.5 on 2021-09-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20210905_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptome',
            name='type_symptome',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=5),
        ),
    ]
