# Generated by Django 3.2.5 on 2021-09-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_symptome_type_symptome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptome',
            name='duree',
        ),
    ]
