# Generated by Django 3.2.5 on 2021-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_remove_symptome_duree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='label',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='examen',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
