# Generated by Django 3.2.5 on 2021-09-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_prescriptionexamen_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionexamen',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
