# Generated by Django 3.2.5 on 2021-09-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0009_service'),
        ('consultation', '0011_prescriptionexamen_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.service'),
        ),
    ]
